apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-node
  labels:
    cluster: validators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-node
  template:
    metadata:
      labels:
        app: validator-node
        cluster: validators
    spec:
      initContainers:
      - name: cert-generator
        image: alpine:latest
        command:
          - sh
          - -c
          - |
            apk add --no-cache openssl
            mkdir -p /certs
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout /certs/private-key.pem \
              -out /certs/public-key.pem \
              -subj "/CN=localhost/O=TripCode/C=US"
            chmod 644 /certs/*.pem
        volumeMounts:
        - name: certs-volume
          mountPath: /certs
      containers:
        - name: tc-validator-node
          image: foultrip/validator-node-tripcode:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: ws
          env:
            - name: NODE_ENV
              value: "production"
            - name: HTTP_PORT
              value: "8080"
            - name: WS_PORT
              value: "8081"
            - name: SEED_NODES
              value: "http://seed-node-service:3000"
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: CERTS_PATH
              value: "/app/certs/tls"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: certs-volume
              mountPath: /app/certs/tls
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-data
          emptyDir: {}
        - name: data-volume
          persistentVolumeClaim:
            claimName: validator-node-pvc
        - name: certs-volume
          emptyDir: {}