apiVersion: v1
kind: Service
metadata:
  name: validator-node-service
  labels:
    app: validator-node
    cluster: validators
spec:
  type: NodePort
  selector:
    app: validator-node
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 8080
      nodePort: 30002
    - name: ws
      protocol: TCP
      port: 4001
      targetPort: 8081
      nodePort: 30003