apiVersion: v1
kind: Service
metadata:
  name: seed-node-service
  labels:
    app: seed-node
    cluster: seed-nodes
spec:
  type: NodePort
  selector:
    app: seed-node
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 30000
    - name: ws
      protocol: TCP
      port: 4000
      targetPort: 8081
      nodePort: 30001