apiVersion: v1
kind: Service
metadata:
  name: seed-node-service
  labels:
    app: seed-node
spec:
  type: NodePort # Permite acceso desde fuera del clúster
  selector:
    app: seed-node
  ports:
    - name: http
      protocol: TCP
      port: 3000 # Puerto del servicio
      targetPort: 8080 # Puerto del contenedor
      nodePort: 30000 # Puerto expuesto al exterior (rango 30000-32767)
    - name: ws
      protocol: TCP
      port: 4000 # Puerto del servicio
      targetPort: 8081 # Puerto del contenedor
      nodePort: 30001 # Puerto expuesto al exterior
