apiVersion: v1
kind: Service
metadata:
  name: full-node-service
  labels:
    app: full-node
    cluster: full-nodes
spec:
  type: NodePort
  selector:
    app: full-node
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 8080
      nodePort: 30004
    - name: ws
      protocol: TCP
      port: 4002
      targetPort: 8081
      nodePort: 30005