apiVersion: v1
kind: Service
metadata:
  name: api-node-service
  labels:
    app: api-node
    cluster: api
spec:
  type: NodePort
  selector:
    app: api-node
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 8080
      nodePort: 30006
    - name: ws
      protocol: TCP
      port: 4003
      targetPort: 8081
      nodePort: 30007