apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  labels:
    cluster: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
        cluster: api
    spec:
      containers:
        - name: tc-api-node
          image: api-node-tripcode:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: ws
          env:
            - name: NODE_ENV
              value: "production"
            - name: HTTP_PORT
              value: "8080"
            - name: WS_PORT
              value: "8081"
            - name: SEED_NODES
              value: "http://seed-node-service:3000"
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-data
          emptyDir: {}
        - name: data-volume
          persistentVolumeClaim:
            claimName: api-node-pvc